name: build-site
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'
      
      - name: Install
        run: npm install
        
      - name: Build
        run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-site
          path: dist/
      
      - name: Clear out things
        run: rm -rf ./*
      
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: built-site
      
      - name: Commit and push
        uses: EndBug/add-and-commit@v8
        with:
          message: Build site
          push: true
